---
- name: Playbok for Turbonomic recommended scaling action
  hosts: all
  gather_facts: false
  vars:
    ec2_region: ""
    details: ""
    display_name: ""
    
  tasks:

    - name: Extra_vars - instance type
      ansible.builtin.debug:
        var: instance_type

    - name: Extra_vars - instance id
      ansible.builtin.debug:
        var: instance_id

    - name: Extra_vars - ec2 region
      ansible.builtin.debug:
        var: ec2_region

    - name: Extra_vars - Info
      ansible.builtin.debug:
        var: details

    - name: Extra_vars - display name
      ansible.builtin.debug:
        var: display_name
    - name: Extra_vars - Jira URI
      ansible.builtin.debug:
        var: jira_uri

    - name: Create an issue on Jira using Ansible
      community.general.jira:
        uri: "{{ jira_uri }}"
        #Pode ser utilizado token
        username: "{{ jira_username }}"
        password: "{{ jira_pwd_token }}"
        project: "{{ jira_project }}"
        operation: create
        summary: "Integração Turbonomic x Ansible x Jira"
        description: "{{ action_detailed_description }} \n\n Link Turbonomic: {{ turbonomic_uri }}/{{turbo_action_id}}"
        issuetype: "{{ jira_issuetype }}"
      args:
        fields:
          customfield_31414: "{{ instance_name }}"
          customfield_29963: "{{ action_saving }}"
          customfield_29982: "{{ action_potentialsaving_month }}"
          customfield_29083: "{{ action_potentialsaving_year }}"
      register: issue
      delegate_to: localhost
      
    - name: Atualiza ticket para GCP
      when:  '"GCP" in cloud_account'
      community.general.jira:
        uri: "{{ jira_uri }}"
        #Pode ser utilizado token
        username: "{{ jira_username }}"
        password: "{{ jira_pwd_token }}"
        project: "{{ jira_project }}"
        issue: '{{ issue.meta.key }}'
        operation: update
      args:
        fields:
          customfield_29269: {{ cloud_account }}
          customfield_29271: ""
          customfield_29270: {{ cloud_region }}
          customfield_29828: {{ instance_tag_project }}
        register: issue
      delegate_to: localhost

    - name: Atualiza ticket para AWS
      when:  '"AWS" in cloud_account' 
      community.general.jira:
        uri: "{{ jira_uri }}"
        #Pode ser utilizado token
        username: "{{ jira_username }}"
        password: "{{ jira_pwd_token }}"
        project: "{{ jira_project }}"
        issue: '{{ issue.meta.key }}'
        operation: update
      args:
        fields:
          customfield_29008:  {{ cloud_account }}
          customfield_29010:  "EC2"
          customfield_29009:  {{ cloud_region }}
          customfield_29827:  {{ instance_tag_project }}         
        register: issue
      delegate_to: localhost

    - set_fact:
        incident_number_cached: "{{ issue.meta.key }}"
        cacheable: true

    - ansible.builtin.debug:
        msg: "Ticket criado com as recomendacoes do Turbonomic: {{ issue.meta.key }}"
