---
- name: An example EDA webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000
  rules:
    - name: Say Hello
      condition: event.payload.message == "Who is in my house?"
      action:
        run_playbook:
          name: rickjames.yml
