---
- name: Rulebook Turbonomic Webhook Actions
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Open Jira Ticket for Virtual Machine Scale Action
      condition: 1 == 1
      action:
        run_job_template:
          name: 'Turbonomic EDA Scaling'
          organization: 'Sulamerica'
          job_args:
            extra_vars:
              instance_type: "{{ event['payload']['newEntity']['displayName'] }}"
              instance_id: "{{ event['payload']['target']['vendorIds'][event['payload']['target']['discoveredBy']['displayName']] }}"
              instance_region: "{{ event['payload']['currentLocation']['vendorIds'][event['payload']['currentLocation']['discoveredBy']['displayName']] }}"
