---
- name: Rulebook Turbonomic Webhook Actions
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Open Jira Ticket for Virtual Machine Scale Action
      condition: event.payload.target.className == "VirtualMachine" and event.payload.actionType == "SCALE" 
      action:
        run_job_template:
          name: 'Turbonomic EDA Scaling'
          organization: 'Sulamerica'
          job_args:
            extra_vars:
              turbo_action_id: "{{ event['payload']['actionID'] }}"
              cloud_account:  "{{ event['payload']['target']['aspects']['cloudAspect']['businessAccount']['displayName'] }}"
              cloud_region: "{{ event['payload']['currentLocation']['vendorIds'][event['payload']['currentLocation']['discoveredBy']['displayName']] }}"
              instance_type: "{{ event['payload']['newEntity']['displayName'] }}"
              instance_id: "{{ event['payload']['target']['vendorIds'][event['payload']['target']['discoveredBy']['displayName']] }}"
              instance_region: "{{ event['payload']['currentLocation']['vendorIds'][event['payload']['currentLocation']['discoveredBy']['displayName']] }}"
              instance_tag_project: "{{ event['payload']['target']['tags']['projeto'] }}"
              instance_tag_owner: "{{ event['payload']['target']['tags']['owner'] }}"
              action_saving : "{{ (event['payload']['stats'][0]['value']) | abs | round(2,'common') }}"
              action_potentialsaving_month : "{{ (event['payload']['stats'][0]['value'] * 730) | abs | round(2,'common') }}"
              action_potentialsaving_year : "{{ (event['payload']['stats'][0]['value'] * 730 * 12) | abs | round(2,'common') }}"
              action_detailed_description : "*Turbonomic Recomenda:* {{ event['payload']['details'] }}\n
*Motivo:* {{ event['payload']['risk']['subCategory'],event['payload']['risk']['subCategory'] }}\n\n
*Cloud Provider:* {{ event['payload']['target']['discoveredBy']['type'] }}\n
*Conta:* {{ event['payload']['target']['aspects']['cloudAspect']['businessAccount']['displayName'] }}\n
*AccID:* {{ event['payload']['target']['aspects']['cloudAspect']['businessAccount']['uuid'] }}\n
*Identificador da instância:* {{ event['payload']['target']['uuid'] }}\n
*Nome da instância:* {{ event['payload']['target']['displayName'] }}\n
*Tipo da instância Atual:* {{ event['payload']['currentEntity']['displayName'] }}\n
*Tipo da instância Recomendada:* {{ event['payload']['newEntity']['displayName'] }}\n
*Economia Mensal Estimada:* US$ {{ (event['payload']['stats'][0]['value'] * 730) | abs | round(2,'common') }} \n
*Economia Anual Estimada:* US$ {{ (event['payload']['stats'][0]['value'] * 730 * 12) | abs | round(2,'common') }} \n
*Região:* {{ event['payload']['currentLocation']['vendorIds'][event['payload']['currentLocation']['discoveredBy']['displayName']] }}\n
*UC:*\n
*Projeto:* "{{ event['payload']['target']['tags']['projeto'] }}" \n"
